### ISSUE TITLE
JAR file cannot be opened by double-clicking the JAR file itself

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-2/main#57]
**Describe the bug**
When I tried to run the application by double-clicking the JAR file, it failed as no response is observed and the application is not opened. I had to run the JAR file using my terminal.

**To Reproduce**
1. Go to the location of the JAR file (in this case it's at Desktop)
2. Double-click on the JAR file 

**Expected behavior**
When double-clicking the JAR file, it is expected that the application is opened and a GUI of the application is displayed for actions.

**Screenshots**
![image](https://user-images.githubusercontent.com/35769004/55452946-65dba300-560c-11e9-87ae-619567ebd6f4.png)
This is the screenshot of the faulty JAR file

**Additional context**
The JAR file is runnable through Terminal.  Navigate to the location of the JAR file. Type 'java -jar LIFE.jar`

<hr>

**Reported by:** @warheade
**Severity:** High

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#10]</sub>

**Comment by jayrometan** [comment]
Thanks for notifying!

**Comment by wongyuqi** [comment]
JAR file could be opened normally.
