### ISSUE TITLE
addTask Command faulty

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-2/main#59]
**Describe the bug**
Error when trying to add a task: Could not save data to file: java.nio.file.AccessDeniedException: C:\WINDOWS\system32\data

**To Reproduce**
1. Enter `addTask n/Test d/111118 h/1234` in command line
2. See error (displayed above)
Note that the new task appeared, but an error came along with it.

**Expected behavior**
Expected a new task called Test with deadline of 11/11/18 due at 12:34 to appear in Task List *without the above error*.

**Screenshots**
![image](https://user-images.githubusercontent.com/39293260/55453105-22356900-560d-11e9-9504-e3c18b2c4b30.png)

**Additional context**
Referencing #61 and #91 

<hr>

**Reported by:** @rachellim10
**Severity:** High

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#21]</sub>

**Comment by jayrometan** [comment]
![image](https://user-images.githubusercontent.com/34192985/55721385-d2ec9f80-5a35-11e9-8e3f-dc7a17b691aa.png)
It worked perfectly on my computer though! I will check it out again Maybe there are crashes on some computers and we need to fix them!

**Comment by jayrometan** [comment]
Thank you so much for the notification.
