### ISSUE TITLE
List Command is redundant

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-2/main#61]
**Describe the bug**
Running the `list` command does not trigger any action at GUI
all contacts are already displayed in the bottom left panel.

**To Reproduce**
1. Go to 'Main Window'
2. Click on 'Command Box'
3. Enter `list`

**Expected behavior**
The List Command should trigger an action that's observable for the user. 

**Screenshots**
![image](https://user-images.githubusercontent.com/35769004/55453236-a8ea4600-560d-11e9-821a-0b11cbe95875.png)
this is the screenshot after running the list command. Only change is that the GUI says that `Listed all contacts` but no other observable changes

<hr>

**Reported by:** @warheade
**Severity:** Medium

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#34]</sub>

**Comment by wongyuqi** [comment]
List command is used to return to full list, perhaps after using the sort command. Hence, using the list command prior to other commands will result in no observable change.

**Comment by wongyuqi** [comment]
Believe this is of low severity as user has misunderstood the use of list command. This issue does not affect function of product at all.

**Comment by wongyuqi** [comment]
The list command is used to return the entire list of contacts, after using find command or sort command. 
Hence, the severity of this bug is low as it not a bug. The user had misinterpreted.
