### ISSUE TITLE
User Guide command cannot be executed

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-2/main#62]
**Describe the bug**
The User Guide for `editTask` command cannot be executed in the application.
Cause confusion, although, logically speaking the error is correct. 
May want to change the User Guide

**To Reproduce**
1. Go to `editTask` section in the user guide

**Expected behavior**
Based on User Guide the application should work
But application returns an error

**Screenshots**
![image](https://user-images.githubusercontent.com/38567680/55453373-257d2480-560e-11e9-877e-c1c93db797d8.png)
![image](https://user-images.githubusercontent.com/38567680/55453395-434a8980-560e-11e9-9185-8da727d8ad57.png)

<hr>

**Reported by:** @chyeo
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#53]</sub>

**Comment by jayrometan** [comment]
Wow what a mistake by us. Thank you so much for noticing this !
