### ISSUE TITLE
Addpurchase incorrect prefix

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-2/main#63]
**Describe the bug**
User guide states that for `addpurchase` command the heading should be `addpurchase n/ pr/` but in the application it states that it should be in the form of `addpurchase pn/ pr/`

![image](https://user-images.githubusercontent.com/35594538/55453391-3d54a880-560e-11e9-9900-725f8a751297.png)

<hr>

**Reported by:** @khairulhazril
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#54]</sub>

**Comment by weizhonglauw** [comment]
Hi, thanks for pointing the issue out. The user guide has been updated to avoid confusion. To clarify, the correct prefix to enter is "pn".
Thanks for the feedback!
