### ISSUE TITLE
addpurchase command faulty

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-2/main#64]
**Describe the bug**
Error displayed when trying to add a new purchase: Could not save data to file: java.nio.file.AccessDeniedException: C:\WINDOWS\system32\data

**To Reproduce**
1. Enter `addpurchase pn/Purchase pr/1.00` in command line.
2. See error above
Note that the new purchase was added to the Expenditure List, but had such an accompanying error.

**Expected behavior**
For the new purchase to be added to Expenditure List *without* the accompanying error.

**Screenshots**
![image](https://user-images.githubusercontent.com/39293260/55453361-14341800-560e-11e9-9d5e-ed06886e91ac.png)

**Additional context**
Referencing #21 and #91 

<hr>

**Reported by:** @rachellim10
**Severity:** High

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#61]</sub>

**Comment by weizhonglauw** [comment]
Hi, we have tried to fix the error and it worked fine for us. 
Thanks for pointing this error out!
