### ISSUE TITLE
User Guide command is invalid

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-2/main#65]
**Describe the bug**
`addpurchase` command on the User Guide and application has conflicting information

application -> `addpurchase pn/Ice cream pr/1.50 t/from 7-11`
User Guide -> `addpurchase n/Ice cream pr/1.50`

**To Reproduce**
1. Go to User Guide for `addpurchase` command
2. launch application and type `addpurchase` command

**Expected behavior**
Application adds a new purchase

**Screenshots**
![image](https://user-images.githubusercontent.com/38567680/55453561-fb783200-560e-11e9-99bc-6771e96b10cd.png)
![image](https://user-images.githubusercontent.com/38567680/55453573-03d06d00-560f-11e9-9209-1ebc9dcdb52c.png)

<hr>

**Reported by:** @chyeo
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#75]</sub>

**Comment by weizhonglauw** [comment]
Hi, thanks so much for the feedback. Documentation errors have now been modified.\
Thanks for pointing out!
