### ISSUE TITLE
Incorrect error message

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-2/main#66]
**Describe the bug**
When typed in an invalid date, the error message produced is as provided in the screenshot.

**Expected behavior**
Expected the error message to state that it is an invalid date.

**Screenshots**
![image](https://user-images.githubusercontent.com/35594538/55453594-19de2d80-560f-11e9-92b1-14dd114a4e34.png)

<hr>

**Reported by:** @khairulhazril
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#80]</sub>

**Comment by jayrometan** [comment]
Fixed. Thank you so much
