### ISSUE TITLE
command's example in the application is invalid 

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-2/main#67]
**Describe the bug**
`addpurchase` command example is invalid

**To Reproduce**
1. Go to application
2. type `addpurchase`
3. copy paste the example and hit enter

**Expected behavior**
Application adds the new purchase

**Screenshots**
![image](https://user-images.githubusercontent.com/38567680/55453649-4d20bc80-560f-11e9-9ab4-3e9f8e33707f.png)
![image](https://user-images.githubusercontent.com/38567680/55453663-5873e800-560f-11e9-90a7-b7e6a38a2729.png)

<hr>

**Reported by:** @chyeo
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#85]</sub>

**Comment by weizhonglauw** [comment]
Hi, thanks for the feedback, the tag examples have been modified.
Thank you!
