### ISSUE TITLE
Edit Command in User Guide has incorrect format of data

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-2/main#68]
**Describe the bug**
The `Edit` Command section in the user guide contains a format of the command. However it is mistyped as the name is keyed in as `Jerome`

**To Reproduce**
1. Go to 'User Guide'
2. Go to `3.1.3 Edit Task`
3. Check the `format`

**Expected behavior**
Format: editTask 1 [n/TASK_NAME] [d/DEADLINE_DATE] [h/DEADLINE_TIME]

**Screenshots**
![image](https://user-images.githubusercontent.com/35769004/55453688-704b6c00-560f-11e9-8f0f-f37e52d42262.png)

<hr>

**Reported by:** @warheade
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#90]</sub>

**Comment by jayrometan** [comment]
Fixed. Thank you for your feedback!
