### ISSUE TITLE
clearexplist command displays error message

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-2/main#69]
**Describe the bug**
Error displayed when clearing Expenditure List

**To Reproduce**
1. Enter `clearexplist` 
2. See error

**Expected behavior**
Expenditure List is supposed to be deleted completely (which did occur) *without* the above error being shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/39293260/55453684-675a9a80-560f-11e9-89cb-56d10c71e1fe.png)

**Additional context**
Referencing #21 and #61 

<hr>

**Reported by:** @rachellim10
**Severity:** High

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#91]</sub>

**Comment by weizhonglauw** [comment]
Thanks for the feedback! The commands are currently running fine on some computers and not on others, we will take a look at the error and fix them. 
Thank you!
