### ISSUE TITLE
Undo/redo commands

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-2/main#70]
**Describe the bug**
Undo/redo commands only work on the addressbook portion of the app when in the UG its stated to work on any command that modifies the student handbook.

<hr>

**Reported by:** @khairulhazril
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#106]</sub>

**Comment by wongyuqi** [comment]
Apologies for the unclear phrasing.

**Comment by wongyuqi** [comment]
Perhaps, my peer @khairulhazril did not read the UG properly.

![image](https://user-images.githubusercontent.com/47082020/56466313-8c8a3e00-6442-11e9-9274-f220f5996532.png)

**Comment by khairulhazril** [comment]
Hi @wongyuqi, this is the screenshot of your user guide that was used for the mock PE. Notice the lack of the yellow highlighted regions in your picture.

![image](https://user-images.githubusercontent.com/35594538/56486334-dbe77180-6509-11e9-887f-afbfd1f34cc4.png)
