### ISSUE TITLE
addPurchase Command has a serious documentation error

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-2/main#71]
**Describe the bug**
when I key in the following line to add a purchase, it is not executed. 
addpurchase n/Pen pr/100

**To Reproduce**
1. Go to 'Main Window'
2. Click on 'Command box'
3. Type `addpurchase n/Pen pr/100`

**Expected behavior**
A success message is shown with details of the added purchase as well as where can I navigate all the purchase list

**Screenshots**
![image](https://user-images.githubusercontent.com/35769004/55453949-80b01680-5610-11e9-8600-0c79cd7c397d.png)

<hr>

**Reported by:** @warheade
**Severity:** High

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#115]</sub>

**Comment by weizhonglauw** [comment]
Hi, the prefix was intended to be set as "pn", so there's no error in this case. However it will be considered to change the prefix to "n".
Thank you for your suggestion.
