### ISSUE TITLE
Undo Command did not work

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-2/main#72]
**Describe the bug**
Could not undo the action of deleting a task.

**To Reproduce**
1. `addTask n/CS2113T MILESTONE V5 d/290319 h/2359 t/HIGH`.
2. `deleteTask 2`
3. `undo`
4. See error and lack of reappearance of the task in step 1

**Expected behavior**
The task stated in step 1 above is supposed to reappear in Task List as the `deleteTask 2` was undone.

**Screenshots**
![image](https://user-images.githubusercontent.com/39293260/55453812-02537480-5610-11e9-8593-cbffd7bea1a0.png)

**Additional context**
Same issue for undoing commands in general, i.e. after adding a purchase `addpurchase pn/Ice cream pr/1.50 t/test` then `undo`, it shows the same error and is unable to remove that purchase.

<hr>

**Reported by:** @rachellim10
**Severity:** High

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#129]</sub>

**Comment by wongyuqi** [comment]
Perhaps, @rachellim10 did not read the UG properly.

![image](https://user-images.githubusercontent.com/47082020/56466300-65cc0780-6442-11e9-8d73-adc1cb878166.png)
