### ISSUE TITLE
Sample tag given cannot be used

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-2/main#73]
**Describe the bug**
For adding a new purchase, the sample command was `addpurchase pn/Ice cream pr/1.50 t/from 7-11`, however this command did not work as tags have to be alphanumeric.

**To Reproduce**
1. `addpurchase pn/Ice cream pr/1.50 t/from 7-11`
2. See error

**Expected behavior**
A new purchase with the given parameters to be added to Expenditure List.

**Screenshots**
![image](https://user-images.githubusercontent.com/39293260/55454026-d7b5eb80-5610-11e9-9728-17ff5cd3173b.png)

**Additional context**
Minor issue: simply modifying the tag to an acceptable alphanumeric format will reduce confusion for the user.

<hr>

**Reported by:** @rachellim10
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#146]</sub>

**Comment by weizhonglauw** [comment]
Hi, thanks for the feedback. It was a mistake due to the Jar file not being updated for the peer testing. Example tag has been modified.
Thanks!
