### ISSUE TITLE
Command Documentation Error

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-2/main#75]
**Describe the bug**
Similar to the `addTask` documentation error, but I can't find that Bug Report Issue! ><

The User Guide -> `editTask 2 d/300219`
Application returns error, logically speaking should be correct but conflicts with User Guide

**To Reproduce**
1. Enter the command in the application after creating a task

**Expected behavior**
User Guide **states** that command should work

**Screenshots**
![image](https://user-images.githubusercontent.com/38567680/55454272-e5b83c00-5611-11e9-9060-e4475f131391.png)
![image](https://user-images.githubusercontent.com/38567680/55454276-eb158680-5611-11e9-85d9-5b29c0b7e21a.png)

<hr>

**Reported by:** @chyeo
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#163]</sub>

**Comment by jayrometan** [comment]
Hi! Thanks for notifying us about the error. Maybe we should have placed another error message as 
the date you have added is an invalid date in the ddMMyy format! 30th February does not exist.
