### ISSUE TITLE
addpurchase command has no restriction on name entered

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-2/main#76]
**Describe the bug**
The user can key in anything as the purchase name but I think it better to limit it to charaters only for it to make sense.

**To Reproduce**
1. Go to 'Main Window'
2. Click on 'Command Box'
3. Type `addpurchase pn/12 pr/0.12 tag/good`

**Expected behavior**
Prompt the user to enter a valid purchase name in this case

**Screenshots**
![image](https://user-images.githubusercontent.com/35769004/55454264-e18c1e80-5611-11e9-89d3-5d853fd1007c.png)

<hr>

**Reported by:** @warheade
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#175]</sub>

**Comment by weizhonglauw** [comment]
Hi, thanks for your feedback. Purchase name was set to be alphanumerical for inputs such as "bicycle rental for 3hrs".
Due to the nature of the feature not having a description column, such names might be needed. 
Thank you for the suggestion.
