### ISSUE TITLE
User Guide

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-2/main#77]
**Describe the bug**
Picture in the userguide quick start section is using AB3 picture when your product is AB4.

<hr>

**Reported by:** @khairulhazril
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#189]</sub>

**Comment by weizhonglauw** [comment]
userguide has been updated, thanks for your feedback!
