### ISSUE TITLE
Command format not standardised 

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-2/main#78]
**Describe the bug**
Task List commands are in camel case, while Expenditure List commands use lowercase throughout.

**Screenshots**
![image](https://user-images.githubusercontent.com/39293260/55454498-b81fc280-5612-11e9-883c-18aa53e0e988.png)
![image](https://user-images.githubusercontent.com/39293260/55454488-ad652d80-5612-11e9-84e3-4839dcf91edb.png)

<hr>

**Reported by:** @rachellim10
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#197]</sub>

**Comment by jayrometan** [comment]
Fixed! Thank you for your suggestion and notification!
