### ISSUE TITLE
add contact has bug in detecting invalid input

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-2/main#79]
**Describe the bug**
when the email address is keyed in , the domain name did not check for cases

**To Reproduce**
1. Go to 'Main Window'
2. Click on 'Command Box'
3. Type `add n/sth p/123 e/123@gmail.coM a/www`

**Expected behavior**

**Screenshots**

**Additional context**

<hr>

**Reported by:** @warheade
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#212]</sub>

**Comment by wongyuqi** [comment]
The domain name does not require a case check as emailing platforms are not case sensitive with the domains. Thus, the above example where the domain for e/123@gmail.coM has a capital M, can still be used to log in to gmail.
